const RAG_LABEL = { green: '🟢 On Track', amber: '🟡 At Risk', red: '🔴 Off Track' }
const SEVERITY_LABEL = { high: 'High', medium: 'Medium', low: 'Low' }
const DEP_STATUS_LABEL = { 'on-track': 'On Track', 'at-risk': 'At Risk', blocked: 'Blocked' }

function formatDate(iso) {
  if (!iso) return ''
  try {
    return new Intl.DateTimeFormat('en-US', {
      month: 'long', day: 'numeric', year: 'numeric',
      hour: 'numeric', minute: '2-digit', timeZoneName: 'short',
    }).format(new Date(iso))
  } catch {
    return iso
  }
}

function stepText(item) {
  if (typeof item === 'string') return item
  const owner = item.suggestedOwner ? ` *(${item.suggestedOwner})*` : ''
  return `${item.action}${owner}`
}

export function generateMarkdown(data) {
  const {
    projects = [],
    keyRisks = [],
    executiveDecisions = [],
    keyDependencies = [],
    generatedAt,
  } = data

  const lines = []

  lines.push(`# Executive Project Dashboard`)
  lines.push(``)
  lines.push(`**Generated:** ${formatDate(generatedAt)}`)
  lines.push(``)

  // Summary
  const green = projects.filter(p => p.ragStatus === 'green').length
  const amber = projects.filter(p => p.ragStatus === 'amber').length
  const red   = projects.filter(p => p.ragStatus === 'red').length
  lines.push(`## Portfolio Summary`)
  lines.push(``)
  lines.push(`| Status | Count |`)
  lines.push(`|--------|-------|`)
  lines.push(`| 🟢 On Track | ${green} |`)
  lines.push(`| 🟡 At Risk  | ${amber} |`)
  lines.push(`| 🔴 Off Track | ${red} |`)
  lines.push(`| **Total Projects** | **${projects.length}** |`)
  lines.push(``)

  // Projects
  lines.push(`## Projects`)
  lines.push(``)
  for (const p of projects) {
    lines.push(`### ${p.name}`)
    lines.push(``)
    lines.push(`**Status:** ${RAG_LABEL[p.ragStatus] ?? p.ragStatus}`)
    if (p.statusSummary) lines.push(`  `)
    if (p.statusSummary) lines.push(`${p.statusSummary}`)
    lines.push(``)
    if (p.teams?.length) lines.push(`**Teams:** ${p.teams.join(', ')}`)
    lines.push(``)
    if (p.accomplishments?.length) {
      lines.push(`**Key Accomplishments:**`)
      for (const a of p.accomplishments) lines.push(`- ${a}`)
      lines.push(``)
    }
    if (p.immediateNextSteps?.length) {
      lines.push(`**Immediate Next Steps:**`)
      for (const s of p.immediateNextSteps) lines.push(`- ${stepText(s)}`)
      lines.push(``)
    }
    if (p.longTermNextSteps?.length) {
      lines.push(`**Long-Term Next Steps:**`)
      for (const s of p.longTermNextSteps) lines.push(`- ${stepText(s)}`)
      lines.push(``)
    }
  }

  // Executive Decisions
  if (executiveDecisions.length) {
    lines.push(`## Executive Decisions Required`)
    lines.push(``)
    lines.push(`| Decision | Projects | Urgency | Owner | Context |`)
    lines.push(`|----------|----------|---------|-------|---------|`)
    for (const d of executiveDecisions) {
      const projects = (d.affectedProjects || []).join(', ')
      const owner = d.suggestedOwner || '—'
      const context = (d.context || '—').replace(/\|/g, '\\|')
      const desc = d.description.replace(/\|/g, '\\|')
      lines.push(`| ${desc} | ${projects} | ${d.urgency} | ${owner} | ${context} |`)
    }
    lines.push(``)
  }

  // Key Risks
  if (keyRisks.length) {
    lines.push(`## Key Risks`)
    lines.push(``)
    lines.push(`| Risk | Projects | Severity | Mitigation |`)
    lines.push(`|------|----------|----------|------------|`)
    for (const r of keyRisks) {
      const projects = (r.affectedProjects || []).join(', ')
      const mitigation = (r.mitigation || '—').replace(/\|/g, '\\|')
      const desc = r.description.replace(/\|/g, '\\|')
      lines.push(`| ${desc} | ${projects} | ${SEVERITY_LABEL[r.severity] ?? r.severity} | ${mitigation} |`)
    }
    lines.push(``)
  }

  // Dependencies
  if (keyDependencies.length) {
    lines.push(`## Key Dependencies`)
    lines.push(``)
    lines.push(`| Dependency | From | To | Status |`)
    lines.push(`|------------|------|----|--------|`)
    for (const d of keyDependencies) {
      const desc = d.description.replace(/\|/g, '\\|')
      lines.push(`| ${desc} | ${d.from} | ${d.to} | ${DEP_STATUS_LABEL[d.status] ?? d.status} |`)
    }
    lines.push(``)
  }

  lines.push(`---`)
  lines.push(`*Generated by Executive Project Dashboard · Powered by Claude AI*`)

  return lines.join('\n')
}

export function downloadMarkdown(data) {
  const md = generateMarkdown(data)
  const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  const date = new Date().toISOString().split('T')[0]
  a.download = `exec-dashboard-${date}.md`
  a.click()
  URL.revokeObjectURL(url)
}
